export const SET_CHARACTER_PAGES = "SET_CHARACTER_PAGES";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_MODAL_CLOSE = "SET_MODAL_CLOSE";
export const SET_CURRENT_FILTER_CHARACTERS = "SET_CURRENT_FILTER_CHARACTERS";